//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/mahmoud/projects/AraCCompilerAntlrVariant/AntlrExamples/AraC.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Parser {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="AraCParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IAraCVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="AraCParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] AraCParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AraCParser.globalVarDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobalVarDecl([NotNull] AraCParser.GlobalVarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AraCParser.funcDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncDecl([NotNull] AraCParser.FuncDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AraCParser.opDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpDecl([NotNull] AraCParser.OpDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AraCParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamList([NotNull] AraCParser.ParamListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IDExpr</c>
	/// labeled alternative in <see cref="AraCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIDExpr([NotNull] AraCParser.IDExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AddressExpr</c>
	/// labeled alternative in <see cref="AraCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddressExpr([NotNull] AraCParser.AddressExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParenthesisExpr</c>
	/// labeled alternative in <see cref="AraCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesisExpr([NotNull] AraCParser.ParenthesisExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MultiplyExpr</c>
	/// labeled alternative in <see cref="AraCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplyExpr([NotNull] AraCParser.MultiplyExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EualityExpr</c>
	/// labeled alternative in <see cref="AraCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEualityExpr([NotNull] AraCParser.EualityExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BxorExpr</c>
	/// labeled alternative in <see cref="AraCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBxorExpr([NotNull] AraCParser.BxorExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AddExpr</c>
	/// labeled alternative in <see cref="AraCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddExpr([NotNull] AraCParser.AddExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CompExpr</c>
	/// labeled alternative in <see cref="AraCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompExpr([NotNull] AraCParser.CompExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BandExpr</c>
	/// labeled alternative in <see cref="AraCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBandExpr([NotNull] AraCParser.BandExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LandExpr</c>
	/// labeled alternative in <see cref="AraCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLandExpr([NotNull] AraCParser.LandExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IndirectionExpr</c>
	/// labeled alternative in <see cref="AraCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndirectionExpr([NotNull] AraCParser.IndirectionExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArrSubScripExpr</c>
	/// labeled alternative in <see cref="AraCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrSubScripExpr([NotNull] AraCParser.ArrSubScripExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LorExpr</c>
	/// labeled alternative in <see cref="AraCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLorExpr([NotNull] AraCParser.LorExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DivExpr</c>
	/// labeled alternative in <see cref="AraCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDivExpr([NotNull] AraCParser.DivExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BorExpr</c>
	/// labeled alternative in <see cref="AraCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBorExpr([NotNull] AraCParser.BorExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SizeExpr</c>
	/// labeled alternative in <see cref="AraCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSizeExpr([NotNull] AraCParser.SizeExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LiteralExpr</c>
	/// labeled alternative in <see cref="AraCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralExpr([NotNull] AraCParser.LiteralExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UnaryBLExpr</c>
	/// labeled alternative in <see cref="AraCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryBLExpr([NotNull] AraCParser.UnaryBLExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SubtractExpr</c>
	/// labeled alternative in <see cref="AraCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubtractExpr([NotNull] AraCParser.SubtractExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CastingExpr</c>
	/// labeled alternative in <see cref="AraCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCastingExpr([NotNull] AraCParser.CastingExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UnaryArithmeticExpr</c>
	/// labeled alternative in <see cref="AraCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryArithmeticExpr([NotNull] AraCParser.UnaryArithmeticExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncCallExpr</c>
	/// labeled alternative in <see cref="AraCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncCallExpr([NotNull] AraCParser.FuncCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AraCParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentList([NotNull] AraCParser.ArgumentListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>assignment_Stat</c>
	/// labeled alternative in <see cref="AraCParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_Stat([NotNull] AraCParser.Assignment_StatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>return_Stat</c>
	/// labeled alternative in <see cref="AraCParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_Stat([NotNull] AraCParser.Return_StatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>result_Stat</c>
	/// labeled alternative in <see cref="AraCParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResult_Stat([NotNull] AraCParser.Result_StatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>if_Stat</c>
	/// labeled alternative in <see cref="AraCParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_Stat([NotNull] AraCParser.If_StatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>while_Stat</c>
	/// labeled alternative in <see cref="AraCParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile_Stat([NotNull] AraCParser.While_StatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>var_Decl</c>
	/// labeled alternative in <see cref="AraCParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_Decl([NotNull] AraCParser.Var_DeclContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression_Stat</c>
	/// labeled alternative in <see cref="AraCParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_Stat([NotNull] AraCParser.Expression_StatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AraCParser.assignmentStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentStat([NotNull] AraCParser.AssignmentStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AraCParser.ifStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStat([NotNull] AraCParser.IfStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AraCParser.whileStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStat([NotNull] AraCParser.WhileStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AraCParser.returnStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStat([NotNull] AraCParser.ReturnStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AraCParser.resultStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResultStat([NotNull] AraCParser.ResultStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AraCParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDecl([NotNull] AraCParser.VarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AraCParser.dataType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDataType([NotNull] AraCParser.DataTypeContext context);
}
} // namespace Parser
